E-feat:web page layout
astrocamp/18th-Moordule pull request #144
Opened 2024-12-14 12:27 UTC by Emma-EC

製作web page頁面
<img width="1267" alt="截圖 2024-12-14 晚上8 26 52" src="https://github.com/user-attachments/assets/3236175e-41be-41d7-8d77-212923fd38d8" />

2024-12-14 14:10 UTC, JoannaLei21 requested changes
讚～～動畫已經做出來了 好棒～
要再麻煩你加一下搜尋bar的 icon （應該在設計票有標示） 
這邊給妳資訊：
加在html的指令: \<i class="fi fi-rr-search-heart">
icon CDN使用方法：
\<link rel='stylesheet' href='[https://cdn-uicons.flaticon.com/2.6.0/uicons-regular-rounded/css/uicons-regular-rounded.css'>](https://cdn-uicons.flaticon.com/2.6.0/uicons-regular-rounded/css/uicons-regular-rounded.css'%3E)

另外現在的檔案有衝突，顯然有兩個\{% block content%}，要記得解衝突喔

2024-12-14 18:13 UTC, JoannaLei21 commented
另外 要討論一下，目前是只有第一個section，後面還有6個section要併進來，現在style寫在一起，除了整體很長之外，會不會影響到後面的設定。

或許style要放在另一個檔案，另外再import進來？

2024-12-15 00:01 UTC, YuHsinTengCindy commented
覺得好像另外寫會比較好,
可以統一使用規格
而且後來考到這樣人家右鍵檢視網頁也不會很赤裸ＸＤ

2024-12-15 08:41 UTC, JoannaLei21 approved these changes

2024-12-15 12:29 UTC, Tingan111 approved these changes

2024-12-16 04:29 UTC, YuHsinTengCindy approved these changes

2024-12-16 08:17 UTC, richart-coder approved these changes

2024-12-16 11:33 UTC, Gary0306 approved these changes

2024-12-16 12:01 UTC, merged