feat:login page layout
astrocamp/18th-Moordule pull request #159
Opened 2024-12-15 08:55 UTC by Emma-EC

新增log in web layout
<img width="1275" alt="截圖 2024-12-15 下午4 55 31" src="https://github.com/user-attachments/assets/b1824842-2642-4d55-b2e1-5eec82faeb60" />

2024-12-15 09:17 UTC, YuHsinTengCindy requested changes
親愛的 名稱單純login會名稱衝突
我們還會有他的login 登入頁面
請改分類成index_login

2024-12-16 02:50 UTC, Adoraxuu commented on pages/templates/pages/index.html
> +        * {
用純CSS嗎?還是之後會改Tailwind?

2024-12-16 08:16 UTC, YuHsinTengCindy approved these changes

2024-12-16 08:17 UTC, JoannaLei21 approved these changes

2024-12-16 08:18 UTC, JoannaLei21 commented on pages/templates/pages/index.html
> +        * {
討論會改Tailwind

2024-12-16 08:19 UTC, Tingan111 approved these changes

2024-12-16 11:02 UTC, merged