R-docs(config): 更新專案依賴與環境設定
astrocamp/18th-Moordule pull request #168
Opened 2024-12-16 07:28 UTC by richart-coder

- 新增 alpinejs 和 htmx 的套件
- 修改 Django 設定檔的環境配置

請將 自己的 .env 改成 
--------------------------------------------------------------------------------------
SECRET_KEY

1.遠端資訊
POSTGRES_DB
POSTGRES_USER
POSTGRES_PASSWORD
POSTGRES_HOST
POSTGRES_POST

2.本地資訊
POSTGRES_DB
POSTGRES_USER
POSTGRES_PASSWORD
POSTGRES_HOST
POSTGRES_POST
--------------------------------------------------------------------------------------
請將自己的 vscode 編輯器改成使用tab空格(Makefile需要)
command + p(指令) ->  >indentation(輸入) -> Convert indentation to Tabs(點擊)

2024-12-16 08:08 UTC, Tingan111 approved these changes

2024-12-16 08:21 UTC, JoannaLei21 approved these changes

2024-12-16 08:32 UTC, Emma-EC approved these changes

2024-12-16 08:47 UTC, YuHsinTengCindy approved these changes

2024-12-16 09:01 UTC, Adoraxuu commented on pydev/settings.py
> +        "NAME": os.getenv("DATABASE_DB"),
PR上寫：
2.本地資訊
POSTGRES_DB
POSTGRES_USER
POSTGRES_PASSWORD
POSTGRES_HOST
POSTGRES_POST

但這裡寫：DATABASE_DB

應該要統一名稱，不然抓不到env的資料

2024-12-16 09:02 UTC, Adoraxuu commented on pydev/settings.py
>          "USER": os.getenv("DATABASE_USER"),
同上

2024-12-16 09:02 UTC, Adoraxuu commented on pydev/settings.py
>          "PASSWORD": os.getenv("DATABASE_PASSWORD"),
同上

2024-12-16 09:02 UTC, Adoraxuu commented on pydev/settings.py
>          "HOST": os.getenv("DATABASE_HOST"),
同上

2024-12-16 09:04 UTC, Adoraxuu requested changes
請修改[.env.example](https://github.com/astrocamp/18th-Moordule/blob/main/.env.example)和PR

2024-12-16 09:41 UTC, richart-coder commented on pydev/settings.py
> +        "NAME": os.getenv("DATABASE_DB"),
ok 已更新 settings.py

2024-12-16 11:33 UTC, Gary0306 approved these changes

2024-12-17 02:35 UTC, Adoraxuu approved these changes

2024-12-17 12:47 UTC, Emma-EC approved these changes

2024-12-17 12:47 UTC, Emma-EC approved these changes

2024-12-18 04:27 UTC, YuHsinTengCindy approved these changes

2024-12-18 07:09 UTC, merged