G-style:index update
astrocamp/18th-Moordule pull request #198
Opened 2024-12-19 10:07 UTC by Gary0306

#149 

首頁切版
<img width="1710" alt="截圖 2024-12-19 下午6 04 23" src="https://github.com/user-attachments/assets/3d27f114-99df-4317-96f7-a1955bbe2dd1" />
<img width="1710" alt="截圖 2024-12-19 下午6 04 28" src="https://github.com/user-attachments/assets/259ffb78-219a-4ea6-a485-f50fade66337" />
<img width="1710" alt="截圖 2024-12-19 下午6 04 31" src="https://github.com/user-attachments/assets/bc0b8831-c936-4e96-9528-61cc358b54a0" />
<img width="1710" alt="截圖 2024-12-19 下午6 04 37" src="https://github.com/user-attachments/assets/20b08b19-7429-4265-98a4-2403e3f328bd" />
<img width="1710" alt="截圖 2024-12-19 下午6 04 39" src="https://github.com/user-attachments/assets/9d277c93-3f09-4304-9be1-ebe7fb06ca21" />

2024-12-19 11:30 UTC, JoannaLei21 requested changes

2024-12-19 11:30 UTC, JoannaLei21 commented on pages/templates/pages/index.html
> +<body class="bg-white text-gray-900">
Layout.html 已經有<body>了
開動的位置是在<body>裡面，
所以這編的body因該改成div

Layout.html:
<body>
{% block content %}  {% endblock %}
</body>

2024-12-20 02:59 UTC, Gary0306 commented on pages/templates/pages/index.html
> +<body class="bg-white text-gray-900">
已修改

2024-12-20 05:48 UTC, JoannaLei21 approved these changes

2024-12-20 05:49 UTC, Emma-EC commented
首頁的動畫應該是垂直移動，目前看起來水平移動？

2024-12-20 08:21 UTC, Tingan111 approved these changes

2024-12-20 08:21 UTC, Emma-EC approved these changes

2024-12-20 08:21 UTC, YuHsinTengCindy approved these changes

2024-12-20 08:21 UTC, richart-coder approved these changes

2024-12-20 08:22 UTC, merged