fix:thrid party login and register
astrocamp/18th-Moordule pull request #273
Opened 2024-12-31 07:03 UTC by Emma-EC

- [ ]  修改google登入按鈕跳轉功能

- [ ] 修改google註冊按鈕跳轉功能

https://github.com/user-attachments/assets/6c4c5504-c5f3-4d0f-9df3-54fab28be1d3

2024-12-31 09:03 UTC, Tingan111 approved these changes

2024-12-31 09:08 UTC, richart-coder approved these changes

2024-12-31 09:18 UTC, Gary0306 approved these changes

2025-01-01 13:48 UTC, JoannaLei21 requested changes

2025-01-01 13:48 UTC, JoannaLei21 commented on .env.example
> +SOCIALACCOUNT_PROVIDERS = {
這下面不需要，要放這兩個：
SOCIAL_AUTH_GOOGLE_CLIENT_ID
SOCIAL_AUTH_GOOGLE_SECRET

2025-01-01 13:54 UTC, JoannaLei21 commented on users/templates/users/components/signin_form.html
> +	{% load socialaccount %}
這個是執行哪個功能

2025-01-02 03:17 UTC, merged